#!/bin/bash
# =====================================================
# init.sh - Inicialitza el backend de Terraform
# =====================================================
# Ús: ./init.sh [PROJECT_NAME]
#      Si no s'especifica, usa "cloud-cv-asix"
# =====================================================

set -e

if [ -t 1 ]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    NC='\033[0m'
else
    RED=''
    GREEN=''
    YELLOW=''
    NC=''
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/terraform"

PROJECT_NAME="${1:-cloud-cv-asix}"
AWS_REGION="${AWS_REGION:-us-east-1}"

echo -e "${GREEN}================================================${NC}"
echo -e "${GREEN}   Terraform Backend Initialization${NC}"
echo -e "${GREEN}   Projecte: ${PROJECT_NAME}${NC}"
echo -e "${GREEN}================================================${NC}"
echo ""

echo -e "${YELLOW}[1/4] Verificant credencials AWS...${NC}"
if ! aws sts get-caller-identity > /dev/null 2>&1; then
    echo -e "${RED}ERROR: Credencials AWS no valides${NC}"
    exit 1
fi
AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
echo -e "${GREEN}   AWS Account: $AWS_ACCOUNT${NC}"

BUCKET_NAME="${PROJECT_NAME}-tfstate-${AWS_ACCOUNT}"

echo -e "${YELLOW}[2/4] Verificant bucket S3...${NC}"
if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
    echo -e "${GREEN}   Bucket $BUCKET_NAME ja existeix${NC}"
else
    echo -e "${YELLOW}   Creant bucket $BUCKET_NAME...${NC}"
    aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$AWS_REGION" > /dev/null
    echo -e "${GREEN}   Bucket creat${NC}"
fi

echo -e "${YELLOW}[3/4] Generant backend.tf...${NC}"
cat > "$TERRAFORM_DIR/backend.tf" << EOF
# =====================================================
# Backend Configuration - Auto-generated by init.sh
# =====================================================
terraform {
  backend "s3" {
    bucket       = "${BUCKET_NAME}"
    key          = "${PROJECT_NAME}/terraform.tfstate"
    region       = "${AWS_REGION}"
    use_lockfile = true
    encrypt      = true
  }
}
EOF
echo -e "${GREEN}   backend.tf generat${NC}"

echo -e "${YELLOW}[4/4] Inicialitzant Terraform...${NC}"
cd "$TERRAFORM_DIR"
terraform init -reconfigure

echo ""
echo -e "${GREEN}================================================${NC}"
echo -e "${GREEN}   Backend inicialitzat correctament!${NC}"
echo -e "${GREEN}================================================${NC}"
echo -e "   Bucket: ${YELLOW}$BUCKET_NAME${NC}"
echo -e "   Key:    ${YELLOW}${PROJECT_NAME}/terraform.tfstate${NC}"
echo -e "   Regio:  ${YELLOW}$AWS_REGION${NC}"
echo ""
